### ISSUE TITLE
/home/runner/work/gnmic/gnmic/pkg/loaders/file_loader/file_loader.go:201: [file_loader] failed to read targets file

### ISSUE THREAD

**Issue by pree04** [openconfig/gnmic#301]
Hi , I am using gnmi file loader to load remote file and i get the error 
 /home/runner/work/gnmic/gnmic/pkg/loaders/file_loader/file_loader.go:201: [file_loader] failed to read targets file: Get "https://<remote file path>l/raw?private_token=<token>": context deadline exceeded

**Comment by karimra** [comment]
That error means the request timed out. There could be many reasons for that. 
- Check that the http server is reachable from gnmic server/container/pod. 
- Check if the http server you run has tls enabled or not and configure the loader accordingly.

**Comment by pree04** [comment]
@karimra 
1. Check that the http server is reachable from gnmic server/container/pod. ->for this i added http_proxy in gnmi env variable, 

but how will i check from the gnmic server/container/pod ? curl is not available and even i am unable to do apk add curl there 
2. Check if the http server you run has tls enabled or not and configure the loader accordingly. -> since from test pods i am able to curl /home/runner/work/gnmic/gnmic/pkg/loaders/file_loader/file_loader.go:201: [file_loader] failed to read targets file: Get "https://l/raw?private_token=generated token value" and i get the file content without passing tls and without using -k . 
I feel the way I am passing the token is not correct. Internally gnmi is doing  url.Parse(path) . When i do the parse seperately i get the error panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/tmp/sandbox2191370610/prog.go:31 +0x4a5

**Comment by karimra** [comment]
If your http server does not have TLS enabled try with a url with scheme `http://` not `https://`

**Comment by pree04** [comment]
No , we need to use https only, but i already set the skip-verify: true

**Comment by karimra** [comment]
can you share your loader config here, so we are on the same page?

**Comment by pree04** [comment]
insecure: true    
loader:
  type: file
  path: https://<gitlab.com>/api/v4/projects/222/repository/files/test%2ftargets.yaml/raw?private_token=23122432424
   interval: 30s

**Comment by karimra** [comment]
maybe replace that `%2f` with `/`, the url parsing will do that for you.

**Comment by pree04** [comment]
@karimra  url parsing works fine for the url https://<gitlab.com>/api/v4/projects/222/repository/files/test%2ftargets.yaml/raw?private_token=23122432424
but how can i test from gnmi this url is accessible?

**Comment by karimra** [comment]
That depends on your setup, that's out of scope of gnmic.

**Comment by pree04** [comment]
@karimra  I am able to do the curl <url> from the test pod and as well as from kubernetes nodes . it seems gnmic pods dont allow to install curl to test it from there.

**Comment by peejaychilds** [comment]
On the node that you are running your gnmic pod you can run curl on the node but in network namespace of the gnmic pod which should tell you if you have some type of issue due to name resolution and/or pod network policy etc.

https://www.redhat.com/sysadmin/container-namespaces-nsenter

Also if the URL works with gnmic outside the pod then the issue is not with gnmic but with your environment ...

**Comment by pree04** [comment]
Can gnmi file loader fetch the file from gilab?

**Comment by pree04** [comment]
From the node where gnmi pods are runing, able to curl <file path url> and get the result from the same gnmi namespace i created a test pod and tried curl <file path url> that is also working
